Repository Team-4yclingHomerun/4yclinghomerun-client, pull requests merged in 2024-09, with the labels that each got.

#2 [FEAT] 섹션 기반 풀페이지 스크롤링을 구현합니다.
  src/components/header/NavigationBar.tsx
  src/hooks/usePageScroll.ts
  src/pages/HomePage.tsx
  src/router/Layout.tsx
Labels: 🚀 feat

#9 [FEAT] 메인페이지에 경기 일정 및 팀 순위를 퍼블리싱합니다.
  package-lock.json
  package.json
  src/assets/home/kt.png
  src/assets/home/lotte.png
  src/components/home/rank/TeamRank.tsx
  src/components/home/schedule/ArrowButton.tsx
  src/components/home/schedule/ScheduleCarousel.tsx
  src/components/home/schedule/ScheduleItem.tsx
  src/components/home/schedule/TeamSchedule.tsx
  src/mocks/home/GameSchedule.ts
  src/pages/HomePage.tsx
  src/styles/carousel/ScheduleCarousel.css
  src/types/ScheduleType.ts
Labels: 🚀 feat

#6 [FEAT] 메인페이지에 hero 섹션을 스크롤 인터랙션으로 구현 합니다
  src/assets/images/home/hero_banner.jpg
  src/assets/images/home/magic_ball.webp
  src/assets/images/home/magic_bat.webp
  src/assets/images/home/winning_kt.webp
  src/assets/images/logo/logo_white.png
  src/components/header/NavigationBar.tsx
  src/components/header/NavigationBarAuth.tsx
  src/components/header/NavigationBarLogo.tsx
  src/components/header/NavigationBarMenu.tsx
  src/components/home/hero/HeroSection.tsx
  src/components/home/hero/HeroSectionBanner.tsx
  src/components/home/hero/HeroSectionBranding.tsx
  src/components/home/hero/HeroSectionDesc.tsx
  src/styles/global.css
Labels: 🚀 feat

#8 [FEAT] 메인페이지에 온라인스토어 상품과 고정 사이드바를 퍼블리싱 합니다.
  package-lock.json
  src/components/shop/Shop.tsx
  src/components/sidebar/SideBar.tsx
Labels: 🚀 feat

#10 [FEAT] 메인페이지에 News 섹션과 이벤트 섹션을 퍼블리싱 합니다.
  src/api/jsonplaceholderdb.ts
  src/assets/logo/KTwiz_logo.svg
  src/components/error/ErrorBoundary.tsx
  src/components/news/NewsArea.tsx
  src/components/news/NewsError.tsx
  src/components/news/NewsItem.tsx
  src/components/news/NewsSkeleton.tsx
  src/hooks/useFetch.ts
  src/types/news.d.ts
  tailwind.config.js
Labels: 🚀 feat

#18 [FEAT] footer 섹션을 퍼블리싱합니다.
  index.html
  src/assets/home/footer-logo.webp
  src/components/footer/Dropdown.tsx
  src/components/footer/DropdownItem.tsx
  src/components/footer/Footer.tsx
  src/components/modal/Modal.tsx
  src/constants/constant.ts
  src/hooks/usePageScroll.ts
  src/mocks/home/FooterDropdownItemList.ts
  src/mocks/home/TermsOfServiceData.ts
  src/pages/HomePage.tsx
Labels: 🚀 feat

#16 [FEAT] 미완성된 팀 스케줄 및 랭킹 섹션을 퍼블리싱합니다.
  index.html
  src/assets/home/footer-logo.webp
  src/common/HoverOverlay.tsx
  src/components/footer/Dropdown.tsx
  src/components/footer/DropdownItem.tsx
  src/components/footer/Footer.tsx
  src/components/home/live/LiveBroadcast.tsx
  src/components/home/rank/TeamRank.tsx
  src/components/home/schedule/ScheduleItem.tsx
  src/components/home/schedule/TeamSchedule.tsx
  src/components/modal/Modal.tsx
  src/constants/constant.ts
  src/hooks/usePageScroll.ts
  src/mocks/home/FooterDropdownItemList.ts
  src/mocks/home/TermsOfServiceData.ts
  src/pages/HomePage.tsx
  src/ui/button/button.tsx
  tailwind.config.js
Labels: 🚀 feat

#28 [CHORE] HTTP 비동기 통신을 처리할 수 있도록 설정파일과 커스텀훅을 세팅합니다
  .gitignore
  package-lock.json
  package.json
  src/api/HttpClient.ts
  src/hooks/useAxios.ts
Labels: 🔧 chore

#31 [BUG] 라우터 경로 이동 시 네비게이션 바 로고 애니메이션 버그를 수정합니다.
  src/common/ScrollToTop.ts
  src/components/header/NavigationBarLogo.tsx
  src/router/Router.tsx
Labels: 💣 bug

#29 [FEAT] 정규 리그 페이지를 퍼블리싱합니다.
  src/assets/game/top_img.webp
  src/assets/team/doosan.png
  src/assets/team/hanhwa.png
  src/assets/team/kia.png
  src/assets/team/kiwoom.png
  src/assets/team/kt.png
  src/assets/team/lg.png
  src/assets/team/lotte.png
  src/assets/team/nc.png
  src/assets/team/samsung.png
  src/assets/team/ssg.png
  src/common/ScrollToTop.ts
  src/components/game/CalendarCell.tsx
  src/components/game/CalendarHeader.tsx
  src/components/game/CalendarView.tsx
  src/components/game/ListView.tsx
  src/components/header/NavigationBarLogo.tsx
  src/hooks/useCalendarGenerate.ts
  src/mocks/game/CalendarScheduleInfo.ts
  src/mocks/game/TeamInfo.ts
  src/pages/GamePage.tsx
  src/router/Router.tsx
  src/types/GameType.ts
Labels: 🚀 feat

#37 [FEAT] 정규 리그 페이지의 박스스코어 페이지를 퍼블리싱합니다.
  package-lock.json
  package.json
  src/api/GetBoxScore.ts
  src/components/game/boxscore/BatterRecordTable.tsx
  src/components/game/boxscore/BoxScoreItem.tsx
  src/components/game/boxscore/BoxScoreSkeleton.tsx
  src/components/game/boxscore/MainRecordTable.tsx
  src/components/game/boxscore/PitcherRecordTable.tsx
  src/components/game/boxscore/ScoreTable.tsx
  src/components/game/boxscore/SectionLayout.tsx
  src/components/game/schedule/CalendarCell.tsx
  src/components/game/schedule/CalendarHeader.tsx
  src/components/game/schedule/CalendarView.tsx
  src/components/game/schedule/ListView.tsx
  src/components/home/contents/schedule/ScheduleItem.tsx
  src/pages/Game/BoxScorePage.tsx
  src/pages/Game/SchedulePage.tsx
  src/stores/ScheduleStore.ts
  src/types/BoxScoreType.ts
  src/ui/table/DataTable.tsx
Labels: 🚀 feat

#35 [FEAT] kt wiz 소개 페이지를 퍼블리싱 합니다
  src/assets/introduction/history_1.jpg
  src/assets/introduction/history_10.jpg
  src/assets/introduction/history_11.jpg
  src/assets/introduction/history_2.jpg
  src/assets/introduction/history_3.jpg
  src/assets/introduction/history_4.jpg
  src/assets/introduction/history_5.jpg
  src/assets/introduction/history_6.jpg
  src/assets/introduction/history_7.jpg
  src/assets/introduction/history_8.jpg
  src/assets/introduction/history_9.jpg
  src/assets/introduction/history_h1_border.png
  src/components/introduction/IntroductionClubItem.tsx
  src/components/introduction/IntroductionHistoryItem.tsx
  src/constants/constant.ts
  src/mocks/introduction/MockIntroductionClub.ts
  src/mocks/introduction/MockIntroductionHistory.ts
  src/pages/Introduction/IntroductionClub.tsx
  src/pages/Introduction/IntroductionHistory.tsx
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/IntroductionPage.tsx
  src/router/Router.tsx
  src/types/IntroductionClub.ts
  src/types/IntroductionHistory.ts
Labels: 🚀 feat

#33 [FEAT] wiz뉴스 페이지를 퍼블리싱합니다.
  .gitignore
  src/assets/wiz-news/top_sub_bg.png
  src/components/common/HoverOverlay.tsx
  src/components/common/ScrollToTop.ts
  src/components/common/layout/DetailPageLayout.tsx
  src/components/common/ui/SearchInput.tsx
  src/components/common/ui/button/button.tsx
  src/components/common/ui/tab/DropTabNavigation.tsx
  src/components/common/ui/tab/TabNavigation.tsx
  src/components/footer/Dropdown.tsx
  src/components/footer/modal/Modal.tsx
  src/components/home/contents/live/LiveBroadcast.tsx
  src/components/home/contents/schedule/ScheduleItem.tsx
  src/components/wiz-news/NewsList.tsx
  src/components/wiz-news/NewsSkeleton.tsx
  src/components/wiz-news/Pagination.tsx
  src/components/wiz-news/WizNews.tsx
  src/hooks/useAxios.ts
  src/mocks/wiz-news/NaverNewsDetail.ts
  src/mocks/wiz-news/WizNewsList.ts
  src/mocks/wiz-news/WizNewsRoomList.ts
  src/mocks/wiz-news/WizPressList.ts
  src/pages/Game/GamePage.tsx
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/NewsPage.tsx
  src/pages/news/NewsDetailPage.tsx
  src/pages/news/NewsPage.tsx
  src/router/Layout.tsx
  src/router/Router.tsx
  src/types/wizNews.d.ts
  src/utils/formattingDate.ts
  tailwind.config.js
Labels: 🚀 feat

#47 [FEAT] 관전 포인트 페이지를 퍼블리싱하여 연동합니다.
  src/api/GetNaverWatchPoint.ts
  src/api/GetPlayerImg.ts
  src/api/GetWatchPoint.ts
  src/components/game/boxscore/SectionLayout.tsx
  src/components/game/watchpoint/common/PlayerAvatar.tsx
  src/components/game/watchpoint/common/PlayerComparisonLayout.tsx
  src/components/game/watchpoint/common/StatComparison.tsx
  src/components/game/watchpoint/common/StatRow.tsx
  src/components/game/watchpoint/lineup/GameLineup.tsx
  src/components/game/watchpoint/lineup/PitcherCard.tsx
  src/components/game/watchpoint/lineup/PlyaerCard.tsx
  src/components/game/watchpoint/lineup/TeamLineup.tsx
  src/components/game/watchpoint/pitcher/PitchTypeBar.tsx
  src/components/game/watchpoint/pitcher/PitcherStatCompareItem.tsx
  src/components/game/watchpoint/skeleton/HotColdZoneSkeleton.tsx
  src/components/game/watchpoint/skeleton/LineupSkeleton.tsx
  src/components/game/watchpoint/skeleton/PitchTypeBarSkeleton.tsx
  src/components/game/watchpoint/skeleton/PitcherSkeleton.tsx
  src/components/game/watchpoint/skeleton/PlayerCompareSkeleton.tsx
  src/components/game/watchpoint/skeleton/TopPlayerSkeleton.tsx
  src/components/game/watchpoint/skeleton/WatchPointSkeleton.tsx
  src/components/game/watchpoint/top-player/HotColdZone.tsx
  src/components/game/watchpoint/top-player/TopPlayerStatCompareItem.tsx
  src/components/game/watchpoint/watchpoint-main/AnimateStat.tsx
  src/components/game/watchpoint/watchpoint-main/WatchPointItem.tsx
  src/hooks/useAxios.ts
  src/pages/game/BoxScorePage.tsx
  src/pages/game/SchedulePage.tsx
  src/pages/game/WatchPointPage.tsx
  src/stores/LineupStore.ts
  src/stores/WatchPointPlayerStore.ts
  src/types/WatchPointType.ts
Labels: 🚀 feat

#55 [FEAT] 정규 리그 > 순위기록 > 투수/타자기록 페이지를 퍼블리싱합니다
  src/api/TopThreePlayerRanking.ts
  src/components/common/ui/SearchInput.tsx
  src/components/common/ui/table/DataTable.tsx
  src/components/game/ranking/player/GameTopPlayerFiveList.tsx
  src/components/game/ranking/player/GameTopPlayerRankingFrame.tsx
  src/components/game/ranking/player/GameTopPlayerThreeFrame.tsx
  src/components/game/ranking/player/GameTopPlayerThreeGroup.tsx
  src/components/game/ranking/player/GameTopPlayerThreeList.tsx
  src/components/game/ranking/player/PlayerRankingTable.tsx
  src/components/game/ranking/player/PlayerRankingTableSection.tsx
  src/components/game/ranking/player/PlayerRankingTabs.tsx
  src/components/game/ranking/player/TopFivePlayerList.tsx
  src/components/game/ranking/player/TopFivePlayerSkeleton.tsx
  src/components/game/ranking/player/TopPlayerRankingFrame.tsx
  src/components/game/ranking/player/TopThreePlayerFrame.tsx
  src/components/game/ranking/player/TopThreePlayerGroup.tsx
  src/components/game/ranking/player/TopThreePlayerImg.tsx
  src/components/game/ranking/player/TopThreePlayerList.tsx
  src/components/game/ranking/player/TopThreePlayerSkeleton.tsx
  src/data/BatterRankingTableData.ts
  src/data/PitcherRankingTableData.ts
  src/data/PlayerRankingData.ts
  src/data/PlayerRankingTableData.ts
  src/pages/game/ranking/PlayerRankingPage.tsx
  src/types/PlayerRanking.ts
Labels: 🚀 feat

#61 [FEAT] Player 페이지와 상세 페이지를 구현합니다.
  eslint.config.js
  src/components/player/CheerCard.tsx
  src/components/player/PlayerCard.tsx
  src/components/player/PlayerItem.tsx
  src/components/player/SectionLayout.tsx
  src/components/player/cheer/CheerError.tsx
  src/components/player/cheer/CheerSkeleton.tsx
  src/components/player/cheer/Profile.tsx
  src/components/player/coach/CoachError.tsx
  src/components/player/coach/CoachSkeleton.tsx
  src/components/player/common/CardArea.tsx
  src/components/player/common/CardError.tsx
  src/components/player/common/CardItem.tsx
  src/components/player/common/CardSkeleton.tsx
  src/components/player/common/DetailSkeleton.tsx
  src/components/player/common/Profile.tsx
  src/components/player/common/ProfileError.tsx
  src/components/player/common/SectionLayout.tsx
  src/components/player/hitter/HitterError.tsx
  src/components/player/hitter/HitterSkeleton.tsx
  src/components/player/hitter/RecentRecordTable.tsx
  src/components/player/hitter/SeasonRecordTable.tsx
  src/components/player/hitter/YearRecordTable.tsx
  src/components/player/pitcher/PitcherError.tsx
  src/components/player/pitcher/PitcherSkeleton.tsx
  src/components/player/pitcher/RecentRecordTable.tsx
  src/components/player/pitcher/SeasonRecordTable.tsx
  src/components/player/pitcher/YearRecordTable.tsx
  src/pages/Player/CheerPage.tsx
  src/pages/Player/CoachPage.tsx
  src/pages/Player/HitterPage.tsx
  src/pages/Player/PitcherPage.tsx
  src/pages/player/PlayerPage.tsx
  src/pages/player/cheer/CheerDetailPage.tsx
  src/pages/player/cheer/CheerPage.tsx
  src/pages/player/coach/CoachDetailPage.tsx
  src/pages/player/coach/CoachPage.tsx
  src/pages/player/hitter/HitterDetailPage.tsx
  src/pages/player/hitter/HitterPage.tsx
  src/pages/player/pitcher/PitcherDetailPage.tsx
  src/pages/player/pitcher/PitcherPage.tsx
  src/router/Router.tsx
  src/types/player.d.ts
  tailwind.config.js
Labels: 🚀 feat
