Repository Team-4yclingHomerun/4yclinghomerun-client, pull requests merged in 2024-10, with the labels that each got.

#66 [FIX] DetailPageLayout, ScrollToTopButton에서 발생하는 버그를 수정합니다.
  src/components/common/layout/DetailPageLayout.tsx
  src/components/common/ui/button/ScrollToTopButton.tsx
Labels: 💣 bug

#70 [REFACTOR] 네비게이션 바 구조를 변경합니다.
  src/assets/community/top_img.jpg
  src/components/auth/common/AuthPageLayout.tsx
  src/components/header/NavigationBar.tsx
  src/components/header/NavigationBarAuth.tsx
  src/components/header/NavigationBarMenu.tsx
  src/components/wiz-park/direction/DirectionMap.tsx
  src/components/wiz-park/direction/DirectionTable.tsx
  src/components/wiz-park/direction/DirectionTitle.tsx
  src/constants/constant.ts
  src/pages/DirectionPage.tsx
  src/pages/community/CommunityPage.tsx
  src/pages/wiz-park/WizParkDirection.tsx
  src/pages/wiz-park/WizParkPage.tsx
  src/router/Router.tsx
Labels: 🔨 refactor, 🌴 style

#71 [FEAT] 로그인/회원가입 폼을 구현합니다.
  package-lock.json
  package.json
  src/assets/auth/vicddory.png
  src/assets/community/top_img.jpg
  src/components/auth/button/GoogleCustomButton.tsx
  src/components/auth/button/GoogleLoginButton.tsx
  src/components/auth/button/KakaoLoginButton.tsx
  src/components/auth/common/AuthPageLayout.tsx
  src/components/auth/common/GoogleAuthHandler.tsx
  src/components/auth/common/KakaoAuthHandler.tsx
  src/components/auth/form/LoginForm.tsx
  src/components/auth/form/SignupForm.tsx
  src/components/auth/schemas/LoginFormSchema.ts
  src/components/auth/schemas/SignupFormSchema.ts
  src/components/common/ui/button/button.tsx
  src/components/common/ui/form/Form.tsx
  src/components/header/NavigationBar.tsx
  src/components/header/NavigationBarAuth.tsx
  src/components/header/NavigationBarMenu.tsx
  src/components/wiz-park/direction/DirectionMap.tsx
  src/components/wiz-park/direction/DirectionTable.tsx
  src/components/wiz-park/direction/DirectionTitle.tsx
  src/constants/constant.ts
  src/hooks/useOAuthHandler.ts
  src/pages/DirectionPage.tsx
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/pages/community/CommunityPage.tsx
  src/pages/wiz-park/WizParkDirection.tsx
  src/pages/wiz-park/WizParkPage.tsx
  src/router/Router.tsx
  src/stores/AuthStore.ts
Labels: 🚀 feat

#72 [FEAT] KT Wiz 팬들이 소통할 수 있는 단체 채팅 페이지를 퍼블리싱합니다
  src/components/community/ChatHeader.tsx
  src/components/community/ChatMessageDisplay.tsx
  src/components/community/ChatMessageForm.tsx
  src/components/community/ChatMessageLoginUser.tsx
  src/components/community/ChatMessageOtherUser.tsx
  src/components/community/ChatMessageTime.tsx
  src/components/community/GuidelinesModalContent.tsx
  src/constants/constant.ts
  src/hooks/useModal.tsx
  src/mocks/community/MockChatMessage.ts
  src/pages/community/ChatPage.tsx
  src/pages/community/CommunityPage.tsx
  src/router/Router.tsx
  src/styles/chat.css
  src/types/ChatMessage.ts
Labels: 🚀 feat

#74 [REFACTOR] 라우터/페이지별 API 에러 핸들링을 구현합니다
  src/api/HttpClient.ts
  src/components/error/ErrorAlert.tsx
  src/components/game/ranking/GameRankingTable.tsx
  src/components/game/ranking/player/PlayerRankingTable.tsx
  src/components/game/ranking/player/PlayerRankingTableSection.tsx
  src/components/game/ranking/player/TopFivePlayerList.tsx
  src/components/game/ranking/player/TopThreePlayerFrame.tsx
  src/components/game/ranking/team/TeamRankingPieGraphFrame.tsx
  src/hooks/useAxios.ts
  src/pages/game/ranking/CrowdRankingPage.tsx
  src/pages/game/ranking/TeamRankingPage.tsx
  src/router/NotFoundPage.tsx
  src/router/Router.tsx
Labels: 🔨 refactor

#75 [FIX] 투수/타자기록 페이지에서 테이블의 탭을 변경할 때마다 테이블 값이 늦게 반영되는 이슈 개선합니다
  src/components/game/ranking/player/PlayerRankingTable.tsx
  src/components/game/ranking/player/PlayerRankingTableSection.tsx
Labels: 🔨 refactor
